### PR TITLE
update to wasi-cli 0.2.0-rc-2023-12-05 snapshot

### LINKED ISSUE #37: WASI wits are outdated
This currently means that wasi-virt cannot be used with components created with `wasm-tools component new`.

### PR DESCRIPTION
**Pull request by whitequark**
This was both surprisingly easy and surprisingly tedious.

I've tested this on Yosys; clocks, environment, stdio, and filesystem (including virtualized mount) all work great. I've never used WASI networking so everything related to it remain as-is, but a cursory check suggests to me that that's probably OK.

Fixes #37.

### CODE REVIEW

**Comment by sunfishcode** [comment]
This looks good to me!

With the Wasmtime update, we'll also want to update wasi-http to the version in Wasmtime, but it has more changes and I'm already working on that in another tree, so I'll take care of that in a follow-up.

**Comment by whitequark** [comment]
Thanks! With this I should be able to migrate [YoWASP](https://yowasp.org) to WASI-Virt and remove quite a lot of manually written resource loading code. I'm really looking forward to that!

Do you know if WASI-Virt is going to be integrated with JCO? That would make it easier to use from my CI scripts.

**Comment by guybedford** [comment]
Thanks @whitequark for your work here! I would actually quite like to introduce a `jco virt` alias for WASI-Virt in JCO, as the project is a JS component toolchain more generally, hoping to get to that but happy to take any PRs in that direction too.

**Comment by whitequark** [comment]
> I would actually quite like to introduce a `jco virt` alias for WASI-Virt in JCO, as the project is a JS component toolchain more generally

I have my hands quite full but if you do introduce this I will deploy it right away in YoWASP.

**Pull request merged**
