### PR TITLE
Rename `wasi:config/runtime` to `wasi:config/store`

### PR DESCRIPTION
**Pull request by scothis**
The `wasi:config/runtime` interface was renamed upstream to `wasi:config/store`. The repository was also renamed from `github.com/WebAssembly/wasi-runtime-config` to
`github.com/WebAssembly/wasi-config`, cementing the shift away from "runtime".

This commit replaces the support for the runtime interface and replaces it with the functionally equivalent store interface. It also removes references to "runtime" config in the readme and CLI help.

Since the interface is still draft and support labeled as experimental, backwards compatibility is not preserved.

Refs https://github.com/WebAssembly/wasi-config/issues/17 https://github.com/bytecodealliance/wasmtime/pull/9404

### CODE REVIEW

**Comment by scothis** [comment]
Keeping as a draft until the wasmtime changes land in a proper release. Although since these are only dev dependencies I wouldn't object to merging earlier if it's desired.

**Comment by guybedford** [comment]
This has now landed in Wasmtime 26 I believe, shall we go ahead and merge?

**Comment by scothis** [comment]
> This has now landed in Wasmtime 26 I believe, shall we go ahead and merge?

Wasmtime 26 still has `wasi:config/runtime`, 27 will have the updated interface.

**Comment by guybedford** [comment]
Great, thank you!

**Pull request merged**
