### PR TITLE
deps: upgrade to latest toolchain

### PR DESCRIPTION
**Pull request by guybedford**
This updates to the latest wasm-tools release, including the Wasmtime upgrade PR in https://github.com/bytecodealliance/wasmtime/pull/6777.

Currently this fails when running `cargo test` on the fs test cases due to the panic at https://github.com/bytecodealliance/wasm-tools/blob/main/crates/wasm-compose/src/encoding.rs#L660.

### CODE REVIEW

**Comment by alexcrichton** [comment]
I've opened https://github.com/bytecodealliance/wasm-tools/issues/1147 to track the panic you're running into here which is from what we discussed on zulip

**Comment by guybedford** [comment]
I've updated this toolchain upgrade PR to the latest dependencies and rebased to main, but now am getting a new error in generating the WIT when running `build-adapter.sh`:

```
error: export parameter required for `wasi:poll/poll`
 --> virtual-adapter/src/lib.rs:6:1
  |
6 | / wit_bindgen::generate!({
7 | |     path: "../wit",
8 | |     world: "virtual-adapter"
9 | | });
  | |__^
  |
  = note: this error originates in the macro `wit_bindgen::generate` (in Nightly builds, run with -Z macro-backtrace for more info)
```

If I then edit the WIT file at `wit/virt.wit` to remove all the interface exports (but leave the imports), then it works.

**Comment by guybedford** [comment]
Ok, so this PR is now failing on the panic - 

```
thread 'virt_test' panicked at 'failed to find alias of TypeId { index: 2, type_size: 1, unique_id: 2 }', /Users/gbedford/.cargo/git/checkouts/wasm-tools-30f99b8fb2d2db27/64fee0e/crates/wasm-compose/src/encoding.rs:660:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by guybedford** [comment]
Tests are finally all passing here. Will merge and release shortly.

**Pull request merged**
