### PR TITLE
Update to wasi-cli@0.2.0

### PR DESCRIPTION
**Pull request by sunfishcode**
Update WASI-virt to wasi-cli@0.2.0-rc-2024-01-16. Several interfaces in wasi-sockets changed, so this updates the virtual-adapter accordingly.

### CODE REVIEW

**Comment by guybedford** [comment]
I think the `virt-deny` / "strip virt" functionality also needs to be updated here for the function signature changes. Ideally we should auto-generate all of this from the WITs, but that work hasn't been done yet so for now those all need to be maintained manually.

**Comment by sunfishcode** [comment]
Yeah, was trying to split out some changes to help isolate a wasm-encoder chage, but split out too much.

**Comment by guybedford** [comment]
@sunfishcode I've pushed some more WIT updates here as well as using the WIT bindgen bug fix at https://github.com/bytecodealliance/wit-bindgen/pull/831 that was necessary to get this to build.

The current failure is now that we use an empty world to build up the full virt world (`virt-base`) but it seems somewhere along the upgrade path, worlds are now being automatically pruned from components, so we likely need to change the strategy in https://github.com/bytecodealliance/WASI-Virt/blob/main/src/lib.rs#L168 where we read the full WIT folder from the binary encoding in the virtual adapter, to ensure that we can definitely find all the worlds that we encoded from the WIT folder instead of them getting automatically pruned in the binary.

**Comment by alexcrichton** [comment]
I've posted https://github.com/sunfishcode/WASI-Virt/pull/1 as an update to this PR which updates the decoding process for the newly-encoded WIT format.

**Comment by guybedford** [comment]
I've updated the PR with @alexcrichton's fix, and can confirm the remaining bugs are now just in the deny and strip virt updates. Will try and push those shortly.

**Pull request merged**
